#!/bin/sh
### BEGIN INIT INFO
# Provides:          dcounter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

. /lib/lsb/init-functions

set -e
set -u

NAME=dcounter
USER=atomx
HOME=/home/$USER
BINARY=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid

OPTS="server"
if [ -f /etc/$NAME.conf ]; then
  OPTS="$OPTS `cat /etc/$NAME.conf | tr '\n' ' '`"
fi

start() {
  echo -n "Starting $BINARY $OPTS"
  touch $PIDFILE
  chown $USER:$USER $PIDFILE
  if start-stop-daemon --start --background --pidfile $PIDFILE --chdir "$HOME" --chuid $USER --exec $BINARY -- $OPTS
  then
    echo " done."
  else
    echo " failed"
  fi
}

stop() {
  echo -n "Stopping $NAME "
  start-stop-daemon --stop --pidfile $PIDFILE --retry=TERM/5/KILL/2
  echo "."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status_of_proc -p $PIDFILE $BINARY $NAME && exit 0
    ;;
  *)
    echo "Usage: "$1" {start|stop|restart|status}"
    exit 1
esac

exit 0

